#!/bin/bash

# Generate comprehensive codebase review
OUTPUT="CODEBASE-REVIEW.md"

echo "# Novelarr Complete Codebase Review" > $OUTPUT
echo "" >> $OUTPUT
echo "Generated: $(date)" >> $OUTPUT
echo "" >> $OUTPUT
echo "## Table of Contents" >> $OUTPUT
echo "1. [Configuration Files](#configuration-files)" >> $OUTPUT
echo "2. [Backend Code](#backend-code)" >> $OUTPUT
echo "3. [Frontend Code](#frontend-code)" >> $OUTPUT
echo "4. [Database Schema](#database-schema)" >> $OUTPUT
echo "" >> $OUTPUT
echo "---" >> $OUTPUT
echo "" >> $OUTPUT

# Configuration Files
echo "## Configuration Files" >> $OUTPUT
echo "" >> $OUTPUT

echo "### docker-compose.yml" >> $OUTPUT
echo '```yaml' >> $OUTPUT
cat docker-compose.yml >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

echo "### Dockerfile" >> $OUTPUT
echo '```dockerfile' >> $OUTPUT
cat Dockerfile >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

echo "### backend/package.json" >> $OUTPUT
echo '```json' >> $OUTPUT
cat backend/package.json >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

echo "### frontend/package.json" >> $OUTPUT
echo '```json' >> $OUTPUT
cat frontend/package.json >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

# Backend Code
echo "## Backend Code" >> $OUTPUT
echo "" >> $OUTPUT

# Main server file
echo "### backend/server.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat backend/server.js >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

# Config
echo "### backend/config/index.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat backend/config/index.js >> $OUTPUT 2>/dev/null || echo "// Config not found"
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

# Database
echo "### backend/db/database.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat backend/db/database.js >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

# Middleware
echo "### backend/middleware/auth.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat backend/middleware/auth.js >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

# Routes
for route in backend/routes/*.js; do
    echo "### $route" >> $OUTPUT
    echo '```javascript' >> $OUTPUT
    cat "$route" >> $OUTPUT
    echo '```' >> $OUTPUT
    echo "" >> $OUTPUT
done

# Services
for service in backend/services/*.js; do
    echo "### $service" >> $OUTPUT
    echo '```javascript' >> $OUTPUT
    cat "$service" >> $OUTPUT
    echo '```' >> $OUTPUT
    echo "" >> $OUTPUT
done

# Frontend Code
echo "## Frontend Code" >> $OUTPUT
echo "" >> $OUTPUT

# Main files
echo "### frontend/src/main.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat frontend/src/main.js >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

echo "### frontend/src/App.vue" >> $OUTPUT
echo '```vue' >> $OUTPUT
cat frontend/src/App.vue >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

echo "### frontend/src/router.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat frontend/src/router.js >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

echo "### frontend/src/api.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat frontend/src/api.js >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

# Store
echo "### frontend/src/stores/auth.js" >> $OUTPUT
echo '```javascript' >> $OUTPUT
cat frontend/src/stores/auth.js >> $OUTPUT
echo '```' >> $OUTPUT
echo "" >> $OUTPUT

# Components
for component in frontend/src/components/*.vue; do
    echo "### $component" >> $OUTPUT
    echo '```vue' >> $OUTPUT
    cat "$component" >> $OUTPUT
    echo '```' >> $OUTPUT
    echo "" >> $OUTPUT
done

# Views
for view in frontend/src/views/*.vue; do
    echo "### $view" >> $OUTPUT
    echo '```vue' >> $OUTPUT
    cat "$view" >> $OUTPUT
    echo '```' >> $OUTPUT
    echo "" >> $OUTPUT
done

# Database Schema
echo "## Database Schema" >> $OUTPUT
echo "" >> $OUTPUT

for migration in backend/db/migrations/*.sql backend/migrations/*.sql; do
    if [ -f "$migration" ]; then
        echo "### $migration" >> $OUTPUT
        echo '```sql' >> $OUTPUT
        cat "$migration" >> $OUTPUT
        echo '```' >> $OUTPUT
        echo "" >> $OUTPUT
    fi
done

echo "---" >> $OUTPUT
echo "" >> $OUTPUT
echo "## File Statistics" >> $OUTPUT
echo "" >> $OUTPUT
echo "- Total Lines of Code: $(find . -name "*.js" -o -name "*.vue" -o -name "*.sql" | grep -v node_modules | xargs wc -l | tail -1 | awk '{print $1}')" >> $OUTPUT
echo "- Backend JS Files: $(find backend -name "*.js" | grep -v node_modules | wc -l)" >> $OUTPUT
echo "- Frontend Vue Files: $(find frontend -name "*.vue" | wc -l)" >> $OUTPUT
echo "- SQL Migration Files: $(find . -name "*.sql" | wc -l)" >> $OUTPUT

echo "" >> $OUTPUT
echo "Generated by generate-codebase-review.sh" >> $OUTPUT